const reviewData = [
  {
    id: 1,
    customer: "Rahul Sharma",
    product: "Gift Box",
    rating: 5,
    review: "Very good product and nice quality.",
    status: "Approved",
  },
  {
    id: 2,
    customer: "Priya Patil",
    product: "Teddy Bear",
    rating: 4,
    review: "Good product. Delivery was fast.",
    status: "Pending",
  },
  {
    id: 3,
    customer: "Amit Kumar",
    product: "Wrist Watch",
    rating: 3,
    review: "Product is okay.",
    status: "Pending",
  },
  {
    id: 4,
    customer: "Sneha Desai",
    product: "Chocolate Box",
    rating: 5,
    review: "Excellent chocolates and beautiful packaging.",
    status: "Approved",
  },
  {
    id: 5,
    customer: "Aniket Patil",
    product: "Flower Bouquet",
    rating: 4,
    review: "Fresh flowers and nice arrangement.",
    status: "Pending",
  },
  {
    id: 6,
    customer: "Neha Joshi",
    product: "Soft Toy",
    rating: 2,
    review: "Quality was not as expected.",
    status: "Rejected",
  },
  {
    id: 7,
    customer: "Rohit Mehta",
    product: "Perfume Gift Set",
    rating: 5,
    review: "Amazing fragrance and premium packaging.",
    status: "Approved",
  },
  {
    id: 8,
    customer: "Kavita Shah",
    product: "Handmade Greeting Card",
    rating: 4,
    review: "Beautiful card with good quality paper.",
    status: "Pending",
  },
  {
    id: 9,
    customer: "Suresh Verma",
    product: "Leather Wallet",
    rating: 3,
    review: "Good wallet but delivery was slightly late.",
    status: "Approved",
  },
  {
    id: 10,
    customer: "Pooja Kulkarni",
    product: "Birthday Gift Hamper",
    rating: 5,
    review: "The gift hamper was perfect for my birthday.",
    status: "Approved",
  },
  {
    id: 11,
    customer: "Vivek Nair",
    product: "Coffee Mug",
    rating: 4,
    review: "Nice design and good quality mug.",
    status: "Pending",
  },
  {
    id: 12,
    customer: "Rahul Sharma",
    product: "Teddy Bear",
    rating: 5,
    review: "Very cute teddy bear. My daughter loved it.",
    status: "Approved",
  },
  {
    id: 13,
    customer: "Priya Patil",
    product: "Wall Clock",
    rating: 2,
    review: "Product arrived with a small scratch.",
    status: "Rejected",
  },
  {
    id: 14,
    customer: "Amit Kumar",
    product: "Artificial Flowers",
    rating: 4,
    review: "Looks beautiful and matches the description.",
    status: "Pending",
  },
  {
    id: 15,
    customer: "Sneha Desai",
    product: "Keychain",
    rating: 3,
    review: "Average product for the price.",
    status: "Pending",
  },
];

export default reviewData;